version: '3.0'

services:
  rate-limiter:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - redis
  redis:
    image: redis:7.2.4
    container_name: rate-limiter-redis
    ports:
      - '6379:6379'
